const myName = 'Avishek';
try 
{
    myName = 'Ataur'
} 
catch (error) 
// catch (er)
// catch (ex)
{
    
}

console.log(myName);
console.log('Manage Error like a gentleman.')